### ISSUE TITLE
Problems with git submodule

### ISSUE THREAD

**Issue by nikolat** [steve02081504/my-gists#1]
When I am developing a project that references this repository as a submodule, I have trouble cloning or updating the submodule.
Can you please give me access to this repository?

**Comment by steve02081504** [comment]
https://github.com/steve02081504/my-gists/invitations

**Comment by nikolat** [comment]
In the end I could not update the submodule.
Anyway, thanks for the update.
![ss](https://user-images.githubusercontent.com/496156/184052159-4603fc8d-6d42-47e1-a330-374cb7bec554.png)

**Comment by steve02081504** [comment]
I was just busy with ghost installer development, so I modified some of the gists but didn't have time to update the tama dependencies
Sorry to have caused you problems

**Comment by nikolat** [comment]
https://github.com/nikolat/tama/commit/bfc1f1b9331d3764bc8b63cc36898fbf450f8038
Resolved.
Sorry for taking up your time.
